### ISSUE TITLE
3.1.1 Modelo

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#15]
**Descripción**
Modelo de la base de datos.
**Tareas a realizar**
- [x] Implementar Base de datos.
- [x] Realizar un documento explicativo de la Base de datos.
- [x] Subir al repositorio. (Dejar la extensión .mwb)
- [x] Revisar relación circular
- [x] Incluir el script de la base de datos
- [x] Revisar valores de conclusiones e indicaciones (aprox 1000).
- [x] Revisar tipos de datos de frecuencias y rangos.

**Comment by wpradere** [comment]
[bd .txt](https://github.com/ISWPOLI/Historias/files/839975/bd.txt)
## Se crea el modelo de la base de datos.

El cual es un archivo que se tiene que re -nombrar en .mwb y se realiza en workbeanch 
@DiegOliveros  quedo pendiente de la invitación para empezar a subir código gracias

**Comment by ingenieriadelsoftware** [comment]
- [ ] Subir al repositorio.

- [ ] incluir scripts, dejar la extensión propia del archivo.

**Comment by jrsosago** [comment]
Las pruebas de Insert se encuentran en la Issue #19

**Comment by wpradere** [comment]
### Se realiza la actualización del repositorio y de la base de datos  👍

**Comment by jrsosago** [comment]
Se cierra está Issue por actividades completas

**Comment by jrsosago** [comment]
**Tareas a realizar:**
- [ ] Corregir formato documento base de datos. Usar el siguiente formato. Con letra color negro. Time new Roman- 12 puntos.

[FormatoIEEE830.docx](https://github.com/ISWPOLI/Historias/files/956982/FormatoIEEE830.docx)

**Comment by jrsosago** [comment]
**Tareas nuevas**
- [ ]  Entidad Relación base de datos.
- [ ] Implementar base de datos.
- [ ] Subir Script base de datos.
- [ ] Realizar documento explicativo base de datos.

- [ ]

**Comment by jrsosago** [comment]
Adjuntó imagen de entidad relación Base de Datos. **Tiempo: 1 hora**
![basedatos](https://user-images.githubusercontent.com/22827594/26906120-bdf99302-4bb0-11e7-98ab-147b1934c1de.PNG)

**Comment by ingenieriadelsoftware** [comment]
Gracias Jeimy, por favor lo tenemos presente para incluir en el documento.


Saludos,


Diego Iván Oliveros Acosta <mailto:dolivero@poligran.edu.co>

Coordinador de la Linea de Ingeniería de Software

Ingeniería de Sistemas y Telecomunicaciones
Facultad de Ingeniería y Ciencias Básicas<http://www.poli.edu.co/ficb/>
Institución Universitaria Politécnico Grancolombiano

Calle 57 # 3-00 este, Bogotá, Colombia
dolivero@poligran.edu.co<mailto:dolivero@poligran.edu.co>

Tel. +57 (1) 745-5555 ext.1267

www.poli.edu.co
www.redilumno.com

<http://cl.s6.exct.net/?qs=4b724a9ae7d42f6f7fc9a439a2d338553c6e2c45b4516124c3fe0565ab7a0e56>[Cobranding]
Este correo y sus anexos pueden ser confidenciales y estar protegidos por derechos de autor, están dirigidos única y exclusivamente para uso de él (los) destinatario(s). Si usted por error lo ha recibido por favor notifíquelo inmediatamente al remitente y destrúyalo de su sistema. No debe copiar, ni imprimir, ni distribuir este correo o sus anexos, ni usarlos para propósito alguno ni dar a conocer su contenido a persona alguna. Las opiniones, conclusiones y otra información contenida en este correo no relacionadas con el negocio oficial del Politécnico Grancolombiano, Institución Universitaria, deben entenderse como personales y de ninguna manera son avaladas por la Institución.
La información transmitida está destinada únicamente a la persona o entidad a quien que va dirigida y puede contener datos confidenciales y/o material privilegiado. Cualquier revisión, retransmisión, difusión u otros usos, o cualquier acción tomada por personas o entidades distintas al destinatario basándose en esta información está prohibida. Si usted recibe este mensaje por error, por favor contacte al remitente y elimine el material de cualquier computadora.



________________________________
De: jrsosago <notifications@github.com>
Enviado: miércoles, 07 de junio de 2017 6:40 p. m.
Para: ISWPOLI/Historias
Cc: OLIVEROS ACOSTA DIEGO IVAN; State change
Asunto: Re: [ISWPOLI/Historias] 3.1.1 Modelo (#15)


Adjuntó imagen de entidad relación Base de Datos. Tiempo: 1 hora
[basedatos]<https://user-images.githubusercontent.com/22827594/26906120-bdf99302-4bb0-11e7-98ab-147b1934c1de.PNG>

**Comment by jrsosago** [comment]
Imagen Base Datos. Tiempo empleado: 2 horas y media
![image](https://user-images.githubusercontent.com/22827594/26912314-20ec5b98-4bd9-11e7-8746-ec9eefd55270.png)

**Comment by jrsosago** [comment]
Se usa el comando show table status para ver los estados de las tablas, a continuación se adjunta el pantallaso.
![image](https://user-images.githubusercontent.com/22827594/26999255-bbb90950-4d5a-11e7-9407-11b61bed432f.png)

**Comment by jrsosago** [comment]
Se realiza documento explicativo de la base de datos y se sube en la rama principal en la carpeta documentos. Se cierra está Issue por actividades terminadas.

**Comment by jrsosago** [comment]
Imagen Base de datos actualizada.
![image](https://user-images.githubusercontent.com/22827594/27202613-e2f4075e-51e7-11e7-8552-9a8967b10a3d.png)

**Comment by jrsosago** [comment]
Imagen de Base de datos Actualizada
![image](https://user-images.githubusercontent.com/22827594/27210064-68007d4c-5215-11e7-8971-fe707f265769.png)
