### ISSUE TITLE
3.1.2 Pruebas-Insert

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#16]
**Descripción**
Realizar Insert en la base de datos y guardar Script pruebas.
**Tareas a realizar**
- [x] Tabla Login
- [x] Tabla Historia Paciente
- [x] Tabla Medicamentos
- [x] Tabla patologías
- [x] Tabla Holter
- [x] Tabla configuración
- [x] Tabla evaluación holter

**Comment by ingenieriadelsoftware** [comment]
Toda historia debe tener un responsable y entregables "Tareas" (-[ ]).
:(

**Comment by jrsosago** [comment]
Adjuntó envió documento explicativo Inserts Base de datos. Se sube a la rama principal los inserts realizados.
[Inserts Base de Datos.pdf](https://github.com/ISWPOLI/Historias/files/954111/Inserts.Base.de.Datos.pdf)

**Comment by jrsosago** [comment]
Se cierra Issue, por tareas realizadas.

**Comment by jrsosago** [comment]
Se reabre está Issue debido a que se revisa la base de datos

**Comment by jrsosago** [comment]
Se realiza adelanto de los insert de prueba. **Tiempo empleado: 50 minutos**

**Comment by jrsosago** [comment]
Se realizan inserts faltantes. **Tiempo empleado:50 minutos** tiempo total empleado 1 hora y 40 minutos. Se cierra está Issue por tareas completadas
