### ISSUE TITLE
3.1.3 Servidor Infraestructura

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#17]
**Descripción**
Realizar cotizaciones servidor de Infraestructura.

**Tareas a realizar**
- [x] Documento definición de los criterios o servicios que debe tener la Infraestructura. @DiegOliveros 
- [x] Realizar cotizaciones basadas en el documento. @DiegOliveros @wpradere @jrsosago

**Comment by wpradere** [comment]
[Documento definición de los criterios o servicios que debe tener la Infraestructura.docx](https://github.com/ISWPOLI/Historias/files/911372/Documento.definicion.de.los.criterios.o.servicios.que.debe.tener.la.Infraestructura.docx)

Se sube Documento con la definición de los criterios o servicios que debe tener la Infraestructura. 
@DiegOliveros @jrsosago 
#42

**Comment by wpradere** [comment]
Se sube información de posibles servidores que se acomodan a las especificaciones técnicas de la aplicación.
Quedo pendiente retroalimentación 

@jrsosago  @DiegOliveros 

- http://marketplace.hpe.com/pdp?catId=15351&reqCatId=3328412&catlevelmulti=15351_3328412_7486465_7500984&prodNum=788076-S01&country=US&locale=en


- http://marketplace.hpe.com/pdp?catId=15351&reqCatId=3328412&catlevelmulti=15351_3328412_7486465_7500984&prodNum=788076-S01&country=US&locale=en


- http://articulo.mercadolibre.com.co/MCO-441200051-servidor-hp-prolaint-dl320e-gen-8-v2-e3-1220v3-4gb-rack-_JM


- http://articulo.mercadolibre.com.co/MCO-438354743-servidor-rack-ibm-system-x-3755-m3-ligeramente-usado-_JM

- articulo.mercadolibre.com.co/MCO-440748638-servidor-hp-proliant-ml110-gen9-_JM

**Comment by DiegOliveros** [comment]
@wpradere consolidar el documento junto con el elaborado por Manuel.
