### ISSUE TITLE
3.2.1 Filtros select *

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#19]
**Descripción**
Realizar filtros select* en la base de datos.
**Tareas a realizar**
- [x] Documento sobre los filtros select a realizar
- [x] Realizar 5 filtros Tabla Login.
- [x] Realizar filtro tabla documento.
- [x] Realizar 3 filtros tabla Historia paciente.
- [x] Realizar filtro tabla medicamentos.
- [x] Realizar filtro tabla historia paciente has medicamentos.
- [x] Realizar filtro tabla patología.
- [x] Realizar filtro tabla historia paciente has patología.
- [x] Realizar filtro tabla Holter.
- [x] Realizar filtro tabla de configuración.
- [x] Realizar dos filtros tabla evaluación holter

**Comment by ingenieriadelsoftware** [comment]
Toda historia debe tener un responsable y entregables "Tareas" (-[ ]).
:(

**Comment by ingenieriadelsoftware** [comment]
Scripts?

**Comment by ingenieriadelsoftware** [comment]
https://technet.microsoft.com/es-es/library/ms191299(v=sql.105).aspx

**Comment by jrsosago** [comment]
Se cierra está Issue por tareas completas.
