### ISSUE TITLE
4.1.2 CSS dispersión de frecuencias

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#23]
**Descripción**
Aplicar estilos CSS a la gráfica de dispersión de frecuencias. Tomar como base Issue #41
**Tareas a realizar**
- [x] Aplicar estilos CSS a la gráfica de dispersión de frecuencias.
- [x] Realizar documento con pantallas del aplicativo.
- [x] Realizar documento final gráfica de dispersión y subirlo a la rama.

**Comment by KmiArthur** [comment]
Se usa imagen de prueba para el mockup por ahora.

**Comment by KmiArthur** [comment]
# Documentación final de gráfica de dispersión
Adjunto en ISSUE #26
