### ISSUE TITLE
4.2.2 CSS regresión lineal y ponderaciones

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#26]
**Descripción**
Aplicar estilos CSS a la gráfica de dispersión de frecuencias. Tomar como base Issue #41
**Tareas a realizar**
- [x] Aplicar estilos CSS a la gráfica de regresión lineal y ponderaciones.
- [x] Realizar documento con pantallas del aplicativo. 
- [x] Realizar documento final gráfica de regresión lineal y ponderaciones, subirlo a la rama.

**Comment by KmiArthur** [comment]
Se usa imagen de prueba para el mockup por ahora.

**Comment by KmiArthur** [comment]
# Documentación final de gráfica de dispersión

[Documentación Gráficas ChartJS.pdf](https://github.com/ISWPOLI/Historias/files/1275476/Documentacion.Graficas.ChartJS.pdf)
