### ISSUE TITLE
0.1.1. Mockups de requerimientos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#41]
**Descripción**
Mockups de la aplicación
**Tareas a realizar**
- [x] Hacer mockups de la aplicación.
- [x] Realizar diagrama de navegación.
- [x] Corregir mockups de la aplicación.

**Comment by jrsosago** [comment]
Se realizan el 80% de los mockups de la aplicación.
[Mockups.pptx](https://github.com/ISWPOLI/Historias/files/840285/Mockups.pptx)

**Comment by jrsosago** [comment]
Se adjunta los mockups de la aplicación totalmente terminados.
[Mockups.pptx](https://github.com/ISWPOLI/Historias/files/842162/Mockups.pptx)

**Comment by ingenieriadelsoftware** [comment]
- [ ] Incluir diagrama de navegación y corregir mockup de imagenes.

**Comment by jrsosago** [comment]
Se cierra está Issue, ya que se terminaron las tareas realizadas en esta Issue

**Comment by jrsosago** [comment]
En el siguiente link se encuentra el mapa de navegación http://prezi.com/vnxspv30my3c/?utm_campaign=share&utm_medium=copy
