### ISSUE TITLE
0.1.2. Ingeniería de requerimientos

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#42]
**Descripción**
Realizar documento de Ingeniería de requerimientos.
**Tareas a realizar**
- [x] Realizar requerimientos de negocio de la aplicación @jrsosago
- [x] Realizar requerimientos funcionales de la aplicación. @jrsosago
- [x] Realizar requerimientos no funcionales de la aplicación @wpradere 
- [x] Realizar requerimientos técnicos de la aplicación. @wpradere

**Comment by jrsosago** [comment]
Adjuntó se envía requerimientos de negocio y requerimientos funcionales de la aplicación. No se sube a la rama principal hasta que no este completo todo el documento.
[IngenieriaDeRequerimientos.xlsx](https://github.com/ISWPOLI/Historias/files/892113/IngenieriaDeRequerimientos.xlsx)

**Comment by wpradere** [comment]
[Requerimientos.xlsx](https://github.com/ISWPOLI/Historias/files/911134/Requerimientos.xlsx)

Se adjunta los requerimientos técnicos y no técnicos

**Comment by jrsosago** [comment]
Se cierra está Issue, por tareas terminadas.
