### ISSUE TITLE
3.1.6 Ajustes en Base de Datos

### ISSUE THREAD

**Issue by KmiArthur** [ISWPOLI/Historias#54]
### Descripción
Realizar ajustes en la base de datos del `Holter`, `HistoriaPaciente` y `Configuración`

### Tareas
- [ ] Holter: Agregar campos de indicaciones, conclusiones.
- [ ] Historia Paciente quitar campos de indicaciones, conclusiones.
- [ ] Configuración: Login_idLogin

**Comment by jrsosago** [comment]
Se cierra está Issue, debido a que también está abierta la Issue #51 para el mismo tema.
